controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint Trajectory Controller
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Velocity Controller
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Effort Controller
    effort_controller:
      type: effort_controllers/JointGroupEffortController

# Joint Trajectory Controller Parameters
joint_trajectory_controller:
  ros__parameters:
    joints:
      - fl_hx
      - fr_hx
      - fr_hy
      - hl_hx
      - hl_hy
      - hl_kn
      - fl_hy
      - hr_hx
      - fl_kn
      - fr_kn
      - hr_hy
      - hr_kn


    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Joint State Broadcaster Parameters
joint_state_broadcaster:
  ros__parameters:
    joints:
      - fl_hx
      - fr_hx
      - fr_hy
      - hl_hx
      - hl_hy
      - hl_kn
      - fl_hy
      - hr_hx
      - fl_kn
      - fr_kn
      - hr_hy
      - hr_kn

# Velocity Controller Parameters
velocity_controller:
  ros__parameters:
    joints:
      - fl_hx
      - fr_hx
      - fr_hy
      - hl_hx
      - hl_hy
      - hl_kn
      - fl_hy
      - hr_hx
      - fl_kn
      - fr_kn
      - hr_hy
      - hr_kn
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

# Effort Controller Parameters
effort_controller:
  ros__parameters:
    joints:
      - fl_hx
      - fr_hx
      - fr_hy
      - hl_hx
      - hl_hy
      - hl_kn
      - fl_hy
      - hr_hx
      - fl_kn
      - fr_kn
      - hr_hy
      - hr_kn
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort